import { useState } from 'react'
import type { City, UtilityType } from '../types'
import type { CreatePayload } from '../store/store'
import { PROVIDERS } from '../engine/providers'

interface Props {
  onSubmit: (p: CreatePayload) => void
  onClose: () => void
}

const CITIES: City[] = ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune']
const UTILITIES: { key: UtilityType; icon: string; label: string }[] = [
  { key: 'electricity', icon: '⚡', label: 'Electricity' },
  { key: 'gas',        icon: '🔥', label: 'Gas' },
  { key: 'water',      icon: '💧', label: 'Water' },
  { key: 'internet',   icon: '📶', label: 'Internet' },
]

const empty: CreatePayload = {
  customerName: '', customerPhone: '', customerEmail: '',
  address: '', city: 'Bangalore', moveInDate: '', utilities: [],
}

function todayISO() { return new Date().toISOString().split('T')[0] }

function addDays(base: string, n: number) {
  const d = new Date(base); d.setDate(d.getDate() + n)
  return d.toISOString().split('T')[0]
}

function daysBetween(a: string, b: string) {
  return Math.round((new Date(b).getTime() - new Date(a).getTime()) / 86400000)
}

function fmtShort(d: string) {
  return new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
}

export function NewCaseModal({ onSubmit, onClose }: Props) {
  const [form, setForm]  = useState<CreatePayload>(empty)
  const [errors, setErr] = useState<Partial<Record<keyof CreatePayload, string>>>({})

  const today      = todayISO()
  const daysToMove = form.moveInDate ? daysBetween(today, form.moveInDate) : null

  // Urgency for move-in date
  const dateUrgency = daysToMove === null ? null
    : daysToMove < 0    ? 'past'
    : daysToMove <= 7   ? 'critical'
    : daysToMove <= 14  ? 'warning'
    : 'ok'

  function toggle(u: UtilityType) {
    setForm(f => ({
      ...f,
      utilities: f.utilities.includes(u) ? f.utilities.filter(x => x !== u) : [...f.utilities, u],
    }))
  }

  function validate() {
    const e: typeof errors = {}
    if (!form.customerName.trim())  e.customerName  = 'Required'
    if (!form.customerEmail.trim()) e.customerEmail = 'Required'
    if (!form.address.trim())       e.address       = 'Required'
    if (!form.moveInDate)           e.moveInDate    = 'Required'
    if (!form.utilities.length)     e.utilities     = 'Select at least one utility'
    setErr(e)
    return !Object.keys(e).length
  }

  function submit(e: React.FormEvent) {
    e.preventDefault()
    if (validate()) onSubmit(form)
  }

  return (
    <div className="fixed inset-0 bg-black/40 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md max-h-[92vh] overflow-y-auto">

        {/* Header */}
        <div className="sticky top-0 bg-white px-6 py-4 border-b border-gray-100 rounded-t-2xl flex items-center justify-between z-10">
          <div>
            <h2 className="text-base font-bold text-gray-900">New Relocation Case</h2>
            <p className="text-xs text-gray-400 mt-0.5">Documents auto-generated by city &amp; utility</p>
          </div>
          <button onClick={onClose}
            className="w-7 h-7 flex items-center justify-center rounded-full text-gray-400 hover:bg-gray-100 text-xl leading-none transition-colors">×</button>
        </div>

        <form onSubmit={submit} className="px-6 py-5 space-y-5">

          {/* Customer */}
          <Section label="Customer Info">
            <Field error={errors.customerName}>
              <input placeholder="Full name *" value={form.customerName}
                onChange={e => setForm(f => ({ ...f, customerName: e.target.value }))}
                className={inp(!!errors.customerName)} />
            </Field>
            <input placeholder="Phone (+91...)" value={form.customerPhone}
              onChange={e => setForm(f => ({ ...f, customerPhone: e.target.value }))}
              className={inp(false)} />
            <Field error={errors.customerEmail}>
              <input placeholder="Email address *" type="email" value={form.customerEmail}
                onChange={e => setForm(f => ({ ...f, customerEmail: e.target.value }))}
                className={inp(!!errors.customerEmail)} />
            </Field>
          </Section>

          {/* Move Details */}
          <Section label="Move Details">
            {/* City */}
            <div>
              <label className="text-xs text-gray-500 font-semibold block mb-1">City *</label>
              <select value={form.city}
                onChange={e => setForm(f => ({ ...f, city: e.target.value as City, utilities: [] }))}
                className={inp(false) + ' bg-white'}>
                {CITIES.map(c => <option key={c}>{c}</option>)}
              </select>
            </div>

            {/* Move-in Date — enriched */}
            <div>
              <label className="text-xs text-gray-500 font-semibold block mb-1">Move-in Date *</label>
              <Field error={errors.moveInDate}>
                <input type="date" value={form.moveInDate} min={today}
                  onChange={e => setForm(f => ({ ...f, moveInDate: e.target.value }))}
                  className={inp(!!errors.moveInDate)} />
              </Field>

              {/* Live date intelligence — appears after date is picked */}
              {form.moveInDate && (
                <div className="mt-2.5 space-y-2">

                  {/* Days countdown chip */}
                  <div className={`flex items-center gap-2.5 px-3.5 py-2.5 rounded-xl border ${
                    dateUrgency === 'past'     ? 'bg-gray-50 border-gray-200' :
                    dateUrgency === 'critical' ? 'bg-red-50 border-red-200' :
                    dateUrgency === 'warning'  ? 'bg-amber-50 border-amber-200' :
                                                 'bg-emerald-50 border-emerald-200'
                  }`}>
                    <span className="text-xl">
                      {dateUrgency === 'past' ? '📅' : dateUrgency === 'critical' ? '🚨' : dateUrgency === 'warning' ? '⚠️' : '✅'}
                    </span>
                    <div className="flex-1">
                      <p className={`text-xs font-bold ${
                        dateUrgency === 'past'     ? 'text-gray-500' :
                        dateUrgency === 'critical' ? 'text-red-700' :
                        dateUrgency === 'warning'  ? 'text-amber-700' :
                                                      'text-emerald-700'
                      }`}>
                        {dateUrgency === 'past'
                          ? `Move-in was ${Math.abs(daysToMove!)} days ago`
                          : daysToMove === 0 ? 'Move-in is today!'
                          : `${daysToMove} days until move-in`}
                      </p>
                      <p className="text-xs text-gray-400">{fmtShort(form.moveInDate)}</p>
                    </div>
                    {dateUrgency === 'critical' && (
                      <span className="text-xs font-bold text-red-600 bg-red-100 px-2 py-0.5 rounded-lg flex-shrink-0">Urgent!</span>
                    )}
                  </div>

                  {/* SLA deadlines per utility */}
                  {form.utilities.length > 0 && (
                    <div className="rounded-xl border border-gray-200 overflow-hidden">
                      <div className="px-3.5 py-2 bg-gray-50 border-b border-gray-100">
                        <p className="text-xs font-bold text-gray-600">📋 SLA Deadlines — must submit by:</p>
                      </div>
                      <div className="divide-y divide-gray-50">
                        {form.utilities.map(u => {
                          const prov = PROVIDERS[form.city]?.[u]
                          if (!prov) return null
                          const deadline    = addDays(form.moveInDate, -prov.slaDays)
                          const daysToSLA   = daysBetween(today, deadline)
                          const slaOverdue  = daysToSLA < 0
                          const slaUrgent   = daysToSLA <= 3 && daysToSLA >= 0
                          return (
                            <div key={u} className={`flex items-center gap-3 px-3.5 py-2.5 ${slaOverdue ? 'bg-red-50' : slaUrgent ? 'bg-amber-50' : ''}`}>
                              <span className="text-sm">
                                {({ electricity:'⚡', gas:'🔥', water:'💧', internet:'📶' })[u]}
                              </span>
                              <div className="flex-1 min-w-0">
                                <p className="text-xs font-semibold text-gray-800 capitalize">{u}</p>
                                <p className="text-xs text-gray-400 truncate">{prov.name}</p>
                              </div>
                              <div className="text-right flex-shrink-0">
                                <p className={`text-xs font-bold ${slaOverdue ? 'text-red-600' : slaUrgent ? 'text-amber-600' : 'text-gray-700'}`}>
                                  {fmtShort(deadline)}
                                </p>
                                <p className={`text-xs ${slaOverdue ? 'text-red-500' : slaUrgent ? 'text-amber-500' : 'text-gray-400'}`}>
                                  {slaOverdue
                                    ? `${Math.abs(daysToSLA)}d already passed`
                                    : daysToSLA === 0 ? 'Due today!'
                                    : `${daysToSLA}d to submit`}
                                </p>
                              </div>
                            </div>
                          )
                        })}
                      </div>
                    </div>
                  )}

                  {/* Visual timeline */}
                  {form.utilities.length > 0 && (
                    <div className="rounded-xl border border-gray-200 px-4 py-3 bg-gray-50">
                      <p className="text-xs font-bold text-gray-500 mb-2.5">Timeline</p>
                      <div className="relative">
                        {/* Track */}
                        <div className="absolute top-2 left-0 right-0 h-0.5 bg-gray-200 rounded-full" />
                        {/* Today marker */}
                        <div className="absolute top-0 flex flex-col items-center" style={{ left: '0%' }}>
                          <div className="w-4 h-4 bg-indigo-600 rounded-full border-2 border-white shadow-sm z-10 relative" />
                          <span className="text-xs text-indigo-600 font-bold mt-1 whitespace-nowrap">Today</span>
                        </div>
                        {/* SLA markers */}
                        {(() => {
                          const totalDays = daysToMove! > 0 ? daysToMove! : 1
                          return form.utilities.map(u => {
                            const prov = PROVIDERS[form.city]?.[u]
                            if (!prov) return null
                            const daysToSLA = daysBetween(today, addDays(form.moveInDate, -prov.slaDays))
                            const pct = Math.min(Math.max((daysToSLA / totalDays) * 100, 5), 85)
                            if (daysToSLA < 0) return null
                            const icon = ({ electricity:'⚡', gas:'🔥', water:'💧', internet:'📶' })[u]
                            return (
                              <div key={u} className="absolute top-0 flex flex-col items-center" style={{ left: `${pct}%` }}>
                                <div className="w-3.5 h-3.5 bg-amber-400 rounded-full border-2 border-white shadow-sm z-10 relative" />
                                <span className="text-xs mt-1">{icon}</span>
                              </div>
                            )
                          })
                        })()}
                        {/* Move-in marker */}
                        <div className="absolute top-0 flex flex-col items-center" style={{ left: '100%', transform: 'translateX(-100%)' }}>
                          <div className="w-4 h-4 bg-emerald-500 rounded-full border-2 border-white shadow-sm z-10 relative" />
                          <span className="text-xs text-emerald-600 font-bold mt-1 whitespace-nowrap">Move-in</span>
                        </div>
                        {/* Spacer */}
                        <div className="h-10" />
                      </div>
                      <div className="flex items-center gap-3 mt-1 flex-wrap">
                        <LegendDot color="bg-indigo-600" label="Today" />
                        <LegendDot color="bg-amber-400" label="SLA deadlines" />
                        <LegendDot color="bg-emerald-500" label="Move-in" />
                      </div>
                    </div>
                  )}

                  {/* Quick warning if SLAs are already overdue */}
                  {form.utilities.some(u => {
                    const prov = PROVIDERS[form.city]?.[u]
                    return prov && daysBetween(today, addDays(form.moveInDate, -prov.slaDays)) < 0
                  }) && (
                    <div className="bg-red-50 border border-red-200 rounded-xl px-3.5 py-3 flex items-start gap-2">
                      <span className="text-red-500 text-sm flex-shrink-0 mt-0.5">⚠</span>
                      <p className="text-xs text-red-700 font-medium leading-relaxed">
                        Some SLA deadlines are already past for this move-in date.
                        This case will be created as <span className="font-bold">Overdue</span> — take action immediately after creating.
                      </p>
                    </div>
                  )}
                </div>
              )}
            </div>

            {/* Address */}
            <Field error={errors.address}>
              <input placeholder="Full address (flat, building, area, city) *" value={form.address}
                onChange={e => setForm(f => ({ ...f, address: e.target.value }))}
                className={inp(!!errors.address)} />
            </Field>
          </Section>

          {/* Utilities */}
          <Section label="Utilities Required *">
            <div className="grid grid-cols-2 gap-2">
              {UTILITIES.map(u => {
                const avail = !!PROVIDERS[form.city]?.[u.key]
                const sel   = form.utilities.includes(u.key)
                return (
                  <button key={u.key} type="button" disabled={!avail} onClick={() => toggle(u.key)}
                    className={`flex items-center gap-2.5 px-3 py-2.5 rounded-xl border text-sm font-medium transition-all ${
                      !avail ? 'border-gray-100 text-gray-300 cursor-not-allowed bg-gray-50'
                      : sel  ? 'border-indigo-400 bg-indigo-50 text-indigo-700 shadow-sm'
                             : 'border-gray-200 text-gray-600 hover:border-indigo-300 hover:bg-indigo-50/40'
                    }`}>
                    <span>{u.icon}</span>
                    <span>{u.label}</span>
                    {sel && <span className="ml-auto text-indigo-500 text-xs">✓</span>}
                    {!avail && <span className="ml-auto text-gray-300 text-xs">N/A</span>}
                  </button>
                )
              })}
            </div>
            {errors.utilities && <p className="text-xs text-red-500 mt-1">{errors.utilities}</p>}

            {/* Provider + doc count preview */}
            {form.utilities.length > 0 && (
              <div className="mt-2 p-3 bg-indigo-50 rounded-xl space-y-1">
                <p className="text-xs font-bold text-indigo-600 mb-1.5">Documents will be auto-generated:</p>
                {form.utilities.map(u => {
                  const prov = PROVIDERS[form.city]?.[u]
                  return prov ? (
                    <div key={u} className="flex items-center justify-between">
                      <p className="text-xs text-indigo-700">
                        <span className="mr-1">
                          {({ electricity:'⚡', gas:'🔥', water:'💧', internet:'📶' })[u]}
                        </span>
                        <span className="font-semibold capitalize">{u}</span>
                        {' — '}{prov.name}
                      </p>
                      <span className="text-xs font-bold text-indigo-500 bg-indigo-100 px-2 py-0.5 rounded-full flex-shrink-0">
                        {prov.docs.length} docs
                      </span>
                    </div>
                  ) : null
                })}
              </div>
            )}
          </Section>

          {/* Actions */}
          <div className="flex gap-3 pt-1">
            <button type="button" onClick={onClose}
              className="flex-1 border border-gray-200 text-gray-600 py-2.5 rounded-xl text-sm font-medium hover:bg-gray-50 transition-colors">
              Cancel
            </button>
            <button type="submit"
              className="flex-1 bg-indigo-600 hover:bg-indigo-700 text-white py-2.5 rounded-xl text-sm font-bold transition-colors shadow-sm">
              Create Case
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

function LegendDot({ color, label }: { color: string; label: string }) {
  return (
    <div className="flex items-center gap-1.5">
      <div className={`w-2.5 h-2.5 rounded-full flex-shrink-0 ${color}`} />
      <span className="text-xs text-gray-500">{label}</span>
    </div>
  )
}

function Section({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2.5">{label}</p>
      <div className="space-y-2">{children}</div>
    </div>
  )
}

function Field({ error, children }: { error?: string; children: React.ReactNode }) {
  return <div>{children}{error && <p className="text-xs text-red-500 mt-0.5">{error}</p>}</div>
}

function inp(err: boolean) {
  return `w-full rounded-xl px-3 py-2.5 text-sm border ${
    err ? 'border-red-300 bg-red-50' : 'border-gray-200'
  } focus:outline-none focus:ring-2 focus:ring-indigo-300 focus:border-indigo-400 transition-colors`
}
